// import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "مرکز خرید آنلاین بانی مد",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body dir="rtl" className='bg-white mx-auto w-full 2xl:container overflow-x-hidden'>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
